version: '3.8'

services:
  frontend:
    image: kanban-dashboard-frontend
    ports:
      - "8080:80" # Expose frontend on host port 8080
    networks:
      - default
      - chatwoot_network

  backend:
    image: kanban-dashboard-backend
    networks:
      - default
      - chatwoot_network

networks:
  chatwoot_network:
    external:
      name: easypanel-tenryu
