version: '3.8'

services:
  app:
    image: kanban-dashboard
    ports:
      - "8080:80" # Expose app on host port 8080
    networks:
      - default
      - chatwoot_network

networks:
  chatwoot_network:
    external:
      name: easypanel-tenryu
